project:
  type: website
  output-dir: docs

website:
  title: "Jessica Kuo's Data Science Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kuo4230
format:
  html:
    theme: cosmo
    css: styles.css



